//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udec_Report
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RptsUdecReportEntities : DbContext
    {
        public RptsUdecReportEntities()
            : base("name=RptsUdecReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ur_evento> ur_evento { get; set; }
        public virtual DbSet<ur_tipoEvento> ur_tipoEvento { get; set; }
        public virtual DbSet<ur_ddlAmbiente> ur_ddlAmbiente { get; set; }
        public virtual DbSet<ur_ddlLugar> ur_ddlLugar { get; set; }
        public virtual DbSet<ur_ddlZona> ur_ddlZona { get; set; }
        public virtual DbSet<ur_imagenR> ur_imagenR { get; set; }
        public virtual DbSet<ur_reportes> ur_reportes { get; set; }
    }
}
