//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udec_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ur_ddlLugar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ur_ddlLugar()
        {
            this.ur_ddlAmbiente = new HashSet<ur_ddlAmbiente>();
        }
    
        public int idLugar { get; set; }
        public string nombreLugar { get; set; }
        public int idZona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ur_ddlAmbiente> ur_ddlAmbiente { get; set; }
        public virtual ur_ddlZona ur_ddlZona { get; set; }
    }
}
