//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udec_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ur_tipoEvento
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int idEvento { get; set; }
    
        public virtual ur_evento ur_evento { get; set; }
    }
}
